# tasks/main.yml
- name: Download and run New Relic installation script
  ansible.builtin.shell: |
    curl -Ls https://download.newrelic.com/install/newrelic-cli/scripts/install.sh | bash

- name: Install New Relic PHP agent
  ansible.builtin.shell: |
    sudo NEW_RELIC_API_KEY={{ newrelic_api_key }} \
    NEW_RELIC_ACCOUNT_ID={{ newrelic_account_id }} \
    NEW_RELIC_REGION={{ newrelic_region }} \
    /usr/local/bin/newrelic install -n php-agent-installer
